# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Proportion of Diagonally Dominant Rows
#' @description Computes the proportion of rows in a square matrix that satisfy diagonal dominance.
#' @name diagonal_dominance_cpp
#' @param mat Numeric matrix (assumed to be square).
#' @return A double representing the proportion of rows that satisfy diagonal dominance.
#' @useDynLib SA24204146
#' @import Rcpp
#' @export
diagonal_dominance_cpp <- function(mat) {
    .Call('_SA24204146_diagonal_dominance_cpp', PACKAGE = 'SA24204146', mat)
}

